# Generated by Django 4.2.4 on 2023-09-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AddField(
            model_name="user",
            name="farm",
            field=models.CharField(blank=True, max_length=30, verbose_name="Farm Name"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
