# Generated by Django 4.2.4 on 2023-10-11 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_imageupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="upload_user",
            field=models.ForeignKey(
                db_column="email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
