# Generated by Django 4.2.4 on 2023-10-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_imageupload_upload_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="location",
            field=models.CharField(
                default="x",
                max_length=1000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="numberImages",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
