# Generated by Django 4.2.4 on 2023-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_remove_imageupload_imageurl_imageupload_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="numberImages",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="number_images",
            field=models.IntegerField(default=0),
        ),
    ]
